from fpdf import FPDF
import io

def export_lens_to_pdf(lens_name, content, deal_name="Deal"):
    """Export a lens view to PDF. Returns bytes."""
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, "PRISM", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, f"{lens_name} View - {deal_name}", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 6, "Confidential - Generated by Prism | tZERO hAIckathon 2026", ln=True)
    pdf.ln(4)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)
    
    # Content - strip markdown, write as plain text
    pdf.set_font("Helvetica", "", 10)
    
    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            pdf.ln(3)
            continue
        
        # Headers
        if stripped.startswith("## "):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 12)
            pdf.multi_cell(0, 7, stripped[3:])
            pdf.set_font("Helvetica", "", 10)
        elif stripped.startswith("# "):
            pdf.ln(2)
            pdf.set_font("Helvetica", "B", 14)
            pdf.multi_cell(0, 8, stripped[2:])
            pdf.set_font("Helvetica", "", 10)
        elif stripped.startswith("- ") or stripped.startswith("* "):
            pdf.multi_cell(0, 6, f"  \u2022 {stripped[2:]}")
        elif stripped.startswith("**") and stripped.endswith("**"):
            pdf.set_font("Helvetica", "B", 10)
            pdf.multi_cell(0, 6, stripped.strip("*"))
            pdf.set_font("Helvetica", "", 10)
        else:
            # Clean any remaining markdown
            clean = stripped.replace("**", "").replace("*", "").replace("`", "")
            try:
                pdf.multi_cell(0, 6, clean)
            except Exception:
                pdf.multi_cell(0, 6, clean.encode("latin-1", "replace").decode("latin-1"))
    
    # Return as bytes
    return bytes(pdf.output())